#! /usr/bin/env bash

# Shows the output of every command
set +x

build_iso_system() {
  nix --extra-experimental-features "nix-command flakes" build .#iso
}

case $1 in
  "iso-system")
    build_iso_system;;
  *)
    echo "Invalid option. Expected 'iso-system'";;
esac
